### ISSUE TITLE
Error in Aiyagari1994

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/vfitoolkit-matlab-replication#3]
Dear Robert,

I tried to run the replication code for **Aiyagari 1994** with Parallel=0
(I was with my laptop and I didn't want to use any parallelization)
and I found a couple of issues

line 124 in Aiyagari1994_Fn could be replaced with 

```
if Parallel==0
    V0=ones(n_a,n_s); %(a,s)
else
    V0=ones(n_a,n_s,'gpuArray'); %(a,s)
end
```

Then in line 152 of Aiyagari1994_Fn the function call is
`SSvalues_AggVars=SSvalues_AggVars_Case1(StationaryDist, Policy,        SSvaluesFn, Params,     SSvalueParamNames, n_d, n_a, n_s, d_grid, a_grid, s_grid, pi_s,p_eqm)`

but the function is 

`SSvalues_AggVars=SSvalues_AggVars_Case1(StationaryDist, PolicyIndexes, SSvaluesFn, Parameters, SSvalueParamNames, n_d, n_a, n_z, d_grid, a_grid, z_grid)`

so Aiyagari1994_Fn calls the function with too many inputs. I think you can safely omit pi_s and p_eqm
(it seems to work fine)

Best,
Alessandro

**Comment by robertdkirkby** [comment]
Have fixed the line 152 aggregate variables (was broken by one of the toolkit version updates). And same for the later Lorenz curves. Thanks for finding these!

I am going to skip adding in the part to allow using the cpu to run the replication just because this will be pretty slow and I'm not sure I want to encourage it ;) That said, I'm glad you did and I guess it will always be an option for expert users :)

**Comment by aledinola** [comment]
You're welcome!
